spring:
  application:
    name: document-processor-service
  datasource:
    url: jdbc:postgresql://localhost:5432/documentdb
    username: joshi
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/



aws:
  s3:
    region: ${AWS_REGION}
    accessKey: ${AWS_ACCESS_KEY}
    secretKey: ${AWS_SECRET_KEY}
s3:
  bucket:
    name: joshi-learning-bucket-2025



